### ISSUE TITLE
Introduce Rest API Stubs in the SA plugin to integrate with Alerting plugin for the transport logic execution 

### ISSUE THREAD

**Issue by getsaurabh02** [opensearch-project/security-analytics#10]
As part of https://github.com/opensearch-project/security-analytics/issues/2 we will need the basic security analytics monitor creation and execution capabilities in the SA plugin. 

Objective : Introduce “Create Monitor API” and “Execute Monitor API” in the Security Analytics Plugin as a basic stubs to complete the end to end integration flow with Alerting.

Details: The objective of these APIs are to introduce the Rest Endpoint in the SA plugin, for the above operations, which can use the heavy lifting logic from the Alerting for creating and executing monitor logic. Rest handling could be done by the SA plugin, whereas the Transport call can be made to Alerting Plugin to execute the Transport Action which the Alerting Plugin already implements. Once the Rest handling is in place we will be able to expand the business logic in the SA plugin side, for specific lifecycle handling of these monitors. We will also need to introduce Unit and Integration Tests for the new changes we are going to add here.

**Comment by okram** [comment]
I have a local fork tracking main/ from this repo and sbcd90's build.gradle alerting/ branch. I have the REST endpoint stubs working. In other words, "stay back! <waving a butter knife around> I got this."

**Comment by okram** [comment]
This is a long winding PR that is only resolved after a series of other PRs are merged in `common-utils/` and `alerting/`. We are currently working through the "model merge" on this PR for those that are intersted:

https://github.com/opensearch-project/common-utils/pull/217
