### ISSUE TITLE
Introduce  and Use “Registration” Logic in Alerting Plugin, for it to allow consumers (such as SA Plugin) to create, execute and manage monitors

### ISSUE THREAD

**Issue by getsaurabh02** [opensearch-project/security-analytics#11]
As part of https://github.com/opensearch-project/security-analytics/issues/2 we will need the Security Analytics plugin to actively interact with the Alerting Plugin for using its framework ability to manage and execute monitors.

Objective: Introduce “Registration” Logic in Alerting Plugin, to make alerting a generic framework, which supports multiple consumers (such as SA Plugin) to create, execute and manage monitors.

Details : The objective here is to isolate Monitor Configuration, Execution and Output workflows of the core Alerting monitors which Alerting Plugin supports by default from new SA monitors. This is important to isolate the regular alerting workflow and its own visualizations dashboard. However, with Alerting being a generic platform we still want to reuse the logic related to monitor configuration and execution in more custom ways. One good way to achieve that is by having a “Registration” logic in Alerting from SA plugin, where it registers itself as one of the consumers and provides it specific configuration required during monitor execution (such as periodicity, new index name for findings/alerts etc). These configurations once registered by Alerting and uniquely identified via an Identifier (Token), can be referenced in all SA --> Alerting calls. 

Tracking issue in the Alerting Plugin : TBD

cc: @lezzago

**Comment by eirsep** [comment]
Alerting cannot cater to use cases of Security Analytics Plugin (SAP) in its current form. SAP would need to define monitors to execute rule pipelines which would need to slice and dice data in more complex ways than supported today. SAP would also need different kinds of queries, triggers and findings to be definable in one monitor execution.

  Alerting needs to evolve into a framework that supports creation of monitors consuming data from different sources, reading rules from a SAP-defined rule index and parsing queries, persisting findings and alerts in custom indices specified by SAP, being able to define more complex queries, triggers and chaining multiple monitors into a single composite execution.


**Milestones we would need to target in Alerting plugin to evolve into a more flexible, customizable and generic framework are presented in the following order of priority**:
[Enhancing monitor configs to plugin custom data sources](https://github.com/opensearch-project/alerting/issues/522)
[Monitor Execution Breakdown](https://github.com/opensearch-project/alerting/issues/523)
[Consuming findings index as data source in monitors](https://github.com/opensearch-project/alerting/issues/525)
[Composite Monitors](https://github.com/opensearch-project/alerting/issues/524)
