### ISSUE TITLE
[Bug]: 2.16.0 boot error because of missing files

### ISSUE THREAD

**Issue by sandervandegeijn** [opensearch-project/security-analytics#1273]
### Describe the bug

During opensearch bootup it's complaining it's missing files for the security analytics plugin:

![image](https://github.com/user-attachments/assets/09047553-57ac-4c64-bb6d-3ce98e9420eb)

Doesn't halt booting but it's ugly. Confirmed on both a kubernetes install and local docker image.

### To reproduce

Boot a fresh 2.16.0 cluster and look for the error

### Expected behavior

No error

### Host / Environment

k8s
local docker desktop
default images

**Comment by gaiksaya** [comment]
Moving to security analytics repo for the maintainers to take a look.

**Comment by dblock** [comment]
[Catch All Triage - [1](https://github.com/dblock), [2](https://github.com/andrross), [3](https://github.com/sandervandegeijn), [4](https://github.com/AmiStrn), [5](https://github.com/udabhas)]

**Comment by sandervandegeijn** [comment]
Apparently there is a PR out there to fix this. Can't find it this instant.
