### ISSUE TITLE
[BUG] Limit of total fields [1000] has been exceeded

### ISSUE THREAD

**Issue by petardz** [opensearch-project/security-analytics#179]
**What is the bug?**

```{"error":{"root_cause":[{"type":"security_analytics_exception","reason":"Limit of total fields [1000] has been exceeded"}],"type":"security_analytics_exception","reason":"Limit of total fields [1000] has been exceeded","caused_by":{"type":"exception","reason":"org.opensearch.alerting.util.AlertingException: Limit of total fields [1000] has been exceeded"}},"status":500}```

**How can one reproduce the bug?**
1. Create 2 indices with 600 fields in mappings: win-log-1, win-log-2
2. Create detector of type WINDOWS for win-log-1
3. Create detector of type WINDOWS for win-log-2
4. See error: "Limit of total fields [1000] has been exceeded"

**What is the expected behavior?**
We shouldn't be limited by index field mapping limits when creating a Detector.

**Do you have any additional context?**

Percolate index used by Detector's monitors require mappings to be copied from source(monitored) index to percolate index, while changing fieldName to "${fieldName}_${indexName}_$monitorId". As we have one percolate index per detector type we can easily overrun limit of total fields in index mappings (default is 1000) of percolate index.

**Suggested solution:**

We would create additional percolate indices if needed and maintain minimal amount of them per Monitor. These are changes in Alerting/CommonUtils to support this:

1. Add following to monitor doc:

    - List of percolate indices for monitor
    - Mappings of source_index --> percolate_index

2. [DocLevelMonitorQueries.indexDocLevelQueries](https://github.com/opensearch-project/alerting/blob/main/alerting/src/main/kotlin/org/opensearch/alerting/util/DocLevelMonitorQueries.kt#L208) - if number of fields of percolate_index would overflow limit:

    - Create new percolate_index(Rollover)
    - Add it to percolate_index list
    - Add mapping: source_index --> new_percolate_index.
    - Update monitor doc.
    - We could also delete all percolate indices here for which source indices are deleted

3. [DocumentLevelMonitorRunner.getMatchedQueries](https://github.com/opensearch-project/alerting/blob/main/alerting/src/main/kotlin/org/opensearch/alerting/DocumentLevelMonitorRunner.kt#L513)

    - resolve correct percolate_index from mappings stored in monitor doc

4. Extend DeleteMonitorAction to delete all created percolate indices

**Comment by petardz** [comment]
PR on alerting repo: https://github.com/opensearch-project/alerting/pull/725/files

**Comment by jaakoob** [comment]
This issue also occurs when using source indicies where `index.mapping.total_fields.limit` is already set to a number above 1000. As far as I understand, the proposed fix will not handle this problem.

**Comment by petardz** [comment]
Good point! We might need to re-adjust this setting on percolate index dynamically so that we don't fail in that situation ever.

**Comment by eirsep** [comment]
Alerting Plugin supports rolling over query index which takes care of this issue
