### ISSUE TITLE
[BUG] Detectors search returns 'no such index' when there are no index created.

### ISSUE THREAD

**Issue by jovancacvetkovic** [opensearch-project/security-analytics#206]
**What is the bug?**
Detectors search returns 'no such index' when there are no indexes created. Status code returned is 404.

**How can one reproduce the bug?**
Deploy OpenSearch, start, and open the application in a browser.
The first page that loads is the overview page
There is a backend API call to http://localhost:5601/_plugins/_security_analytics/detectors/_search
The result of the request is
`
Original server response: statusCode: 404,
  response: '{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [.opensearch-sap-detectors-config]","index":".opensearch-sap-detectors-config","resource.id":".opensearch-sap-detectors-config","resource.type":"index_or_alias","index_uuid":"_na_"}],"type":"index_not_found_exception","reason":"no such index [.opensearch-sap-detectors-config]","index":".opensearch-sap-detectors-config","resource.id":".opensearch-sap-detectors-config","resource.type":"index_or_alias","index_uuid":"_na_"},"status":404}',
`

**What is the expected behavior?**
This should not be an error but a response with status 200 with an empty array response.

**Do you have any screenshots?**
![Custom rules error](https://user-images.githubusercontent.com/28289071/208759725-e7669982-fe6f-42fc-9922-4bfe5322072e.png)

**Comment by ict-one-nl** [comment]
<img width="1473" alt="image" src="https://user-images.githubusercontent.com/2643715/209819159-0f781db6-6610-4fa2-bdef-125cb763151d.png">

Confirmed on a fresh 2.4.1 cluster
