### ISSUE TITLE
Create composite monitor during detector creation

### ISSUE THREAD

**Issue by eirsep** [opensearch-project/security-analytics#220]
Composite monitors run a set of monitors in a sequence. Each detector should create bucket level and doc level monitors as required in a disabled mode and create a composite monitor workflow with a sequence of the above created monitor ids. They can optionally use the findings of one monitor to filter data queried by the next monitor.

- detector creation would involve following interactions with alerting:
 i. create doc level and bucket level monitors as per detector rules in disabled mode.
 ii. create composite monitors with sequence of above created monitor ids.
 iii. populate chained findings field to enable correct creation of detector triggers.
iv. delete all resources if `step i` or `step ii` fail.

**Comment by stevanbz** [comment]
I am working on this. The idea is to create workflow for new detectors and follow the steps @eirsep mentioned in description.

**Comment by stevanbz** [comment]
Followed the steps from the above. The PR that is created for parent issue containing all the changes:
https://github.com/opensearch-project/security-analytics/pull/316

**Comment by getsaurabh02** [comment]
Removing untriaged as this is WIP feature. Lets follow the same for new feature issues @eirsep

**Comment by engechas** [comment]
This functionality is implemented. Closing
