### ISSUE TITLE
Update composite monitor during detector updation

### ISSUE THREAD

**Issue by eirsep** [opensearch-project/security-analytics#222]
When detector is updated, if new monitors are created and/or old monitors are deleted we also need to update the composite monitor sequence.
Update detector flow would involve the following interactions with alerting:
- create new monitors if any
- update sequence of detector's composite monitor by removing old monitor ids(if any monitors need to be deleted) and add new monitor ids
- if step one or two fail delete any newly created monitors, else delete monitors which are not required anymore

**Comment by stevanbz** [comment]
Followed the steps from the above. The PR that is created for parent issue containing all the changes:
https://github.com/opensearch-project/security-analytics/pull/316

**Comment by engechas** [comment]
This functionality is implemented, closing
