### ISSUE TITLE
Delete composite monitor during detector deletion

### ISSUE THREAD

**Issue by eirsep** [opensearch-project/security-analytics#225]
When detector is deleted, bucket/doc level monitors and the composite monitor need to deleted as part of resource clean up.

Delete  detector flow would involve the following interactions with alerting (ORDER MATTERS):
i. Delete the composite monitor first.
ii. Delete the doc/bucket level monitors 
iii. if step i or step ii fail, mark delete detector request as failed.

**Comment by stevanbz** [comment]
Followed the steps from the above. The PR that is created for parent issue containing all the changes:
https://github.com/opensearch-project/security-analytics/pull/316

**Comment by engechas** [comment]
This functionality is implemented. Closing
