### ISSUE TITLE
[FEATURE] Detector Lifecycle Management

### ISSUE THREAD

**Issue by getsaurabh02** [opensearch-project/security-analytics#23]
**Is your feature request related to a problem?**
For Security Analytics to be able to run threat detection on the incoming data, it will rely on the Alerting plugin offering to be able to create and schedule monitors. However for Alerting to act as a pure monitor execution framework, it needs to register external consumer plugins to provide data and workflow isolation.

Although monitors will be maintained by the Alerting plugin, SA needs to be able to keep a view of its created and running detectors (monitors), and expose the same for all SA management operations - such as Detector list/search/get operations. 

It will require constructs, which can be broken down into following tasks:

1. Security Analytics Config Metadata : The persistent store for the SA plugin in form a system index. This holds all the metadata information of the detectors that were created by the SA, along with their current state information (enabled/disabled)/
2. List Detectors API : Rest API in Security Analytics to be able to list/search detectors from the SA congif metadata with the necessary metadata information.
3. Get Detector API : Rest API in Security Analytics which takes the detector ID, and fetches the entire detector (monitor) information from the Alerting via existing internal transport action.

Sample API request response structure (only for reference)
```
GET _plugins/_security_analytics/detectors/{detector_id}

{
  "type": "detector",
  "detector_type": "windows",
  "name": "windows_detector",
  "enabled": true,
  "createdBy": "chip",
  "schedule": {
    "period": {
      "interval": 1,
      "unit": "MINUTES"
    }
  },
  "inputs": [
    {
      "input": {
        "description": "windows detector for security analytics",
        "indices": [
          "windows"
        ],
        "rules": [
          {
            "id": 1,
            "name": ""
          }
        ],
        "rules_count": 1
      }
    }
  ],
  "triggers": []
}
```

**Comment by raj-chak** [comment]
The Detector class in org.opensearch.securityanalytics.model
will be used to encapsulate the Detector object. Sample structure is below:
{
  "type": "detector",
  "detector_type": "windows",
  "name": "windows_detector",
  "enabled": true,
  “monitorId”: “Q9aXOmkBC25HCRGmzfw-",
  "createdBy": "chip",
  "schedule": {
    "period": {
      "interval": 1,
      "unit": "MINUTES"
    }
  },
  "inputs": [
    {
      "input": {
        "description": "windows detector for security analytics",
        "indices": [
          "windows"
        ],
        "rules": [
          {
            "id": 1,
            "name": ""
          }
        ],
        "rules_count": 1
      }
    }
  ],
  "triggers": []
} 

The monitorId attribute is added to define the one to one correspondence between a detector and a monitor.
The name of the index that is persisted that would have this mapping between detector and monitor is ".opensearch-detectors-config"

**Comment by amsiglan** [comment]
Can we add a table describing required vs optional fields in the request similar to [this task](https://github.com/opensearch-project/security-analytics/issues/55). @sbcd90
