### ISSUE TITLE
[BUG] Build fails when running with -Dtests.locale=tr-TR -Dtests.timezone=Australia/Currie parameters

### ISSUE THREAD

**Issue by stevanbz** [opensearch-project/security-analytics#246]
Failing build on backport

The bug happens once SecureFindingRestApiIT is executed with -Dtests.locale=tr-TR -Dtests.timezone=Australia/Currie parameters.

**Build that failed:**
https://github.com/opensearch-project/security-analytics/actions/runs/3851316272/jobs/6562357857#step:8:389
**Error message:**
org.opensearch.client.ResponseException: method [GET], host [https://localhost:9200/], URI [/_plugins/_security_analytics/findings/_search?detectorType=TEST_W%C4%B0NDOWS], status line [HTTP/1.1 400 Bad Request]
    {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"No enum constant org.opensearch.securityanalytics.model.Detector.DetectorType.TEST_WİNDOWS"}],"type":"illegal_argument_exception","reason":"No enum constant org.opensearch.securityanalytics.model.Detector.DetectorType.TEST_WİNDOWS"

**Solution**
remove from test detector2.getDetectorType().toUpperCase() or add locale when upperCasing

**How can one reproduce the bug?**

**What is the expected behavior?**

**What is your host/environment?**
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by getsaurabh02** [comment]
Can we close this out now @stevanbz ?

**Comment by stevanbz** [comment]
> Can we close this out now @stevanbz ?

Yes. Tnx
