### ISSUE TITLE
[FEATURE] Index Template cleanup

### ISSUE THREAD

**Issue by petardz** [opensearch-project/security-analytics#312]
**Is your feature request related to a problem?**
We're using index templates to maintain mappings on all backing indices of index patterns, aliases and datastreams that users are using as input of detector. We need reliable way to delete unused templates.

**What solution would you like?**
When monitor is deleted do following:

1. Fetch all Detectors and compile list of all inputs which are either index pattern, alias or datastream
2. If template doesn't contain any user defined component templates added to it, and no other detector has input which matches template index pattern: delete component and index template

**Comment by getsaurabh02** [comment]
@petardz Is there any pending AI for this post 2.5?

**Comment by engechas** [comment]
Closing as completed by #317
