### ISSUE TITLE
[FEATURE] GetMappingsView - filter unmapped aliases based on currently enabled rules

### ISSUE THREAD

**Issue by petardz** [opensearch-project/security-analytics#313]
**Is your feature request related to a problem?**
GetMappingsView will currently return all unmapped aliases defined in backend mappings files. In situations where user has very few rules selected, it could be overwhelming to map all aliases when user could map just ones used in selected rules.

**What solution would you like?**
1. Add new optional parameter to GetMappingsView API: **detectorId**
2. Filter out all aliases from "unmapped_alias_fields" list where alias is not present in any of rule fields from all rules currently enabled on detector referenced by **_detectorId_**

**Do you have any additional context?**
This would cover both detector create and update flows as every subsequent call to GetMappingsView API would return mappings view which includes unmapped aliases used in all rules currently enabled for specific detector.

We currently store list of fields used by Rule in Rule document, so fetching these would require simple search query. This list is computed during sigma yaml parsing.

**Comment by getsaurabh02** [comment]
We have made improvements in 2.5 for the mapping API. Are there any more pending AIs from here? @petardz 
cc: @amsiglan

**Comment by petardz** [comment]
We agreed on implementing this filtering on FE. 

FE can call SearchRule API to fetch selected rules and their query field names. Beside "unmapped_alias_fields filtering", this information can be used to show user which rules won't work if user doesn't map all fields on "Field Mapping" page

**Comment by engechas** [comment]
Above mentioned issue is closed and comment mentions the filtering will be performed on the frontend. Closing this issue, please reopen if it is not resolved
