### ISSUE TITLE
[BUG][Multi-tenancy] Not able to isolate detectors in security analytics plugin

### ISSUE THREAD

**Issue by jinalp-fens** [opensearch-project/security-analytics#366]
Basically, I have one index named **test**.  The test index has data of all tenants and a "tenantId" field to distinguish data based on which tenant it belongs to. And three users are there as per unique security role mapping.

**User -> Security Role -> Tenant mapping**
admin -> all_access -> admin_tenant
testing1 -> TestingRole01 -> Tenant1
testing2 -> TestingRole02 -> Tenant2

Using the security analytics plugin, I've tried to create a detector using testing1 user, So that detector basically runs on the "test" index and triggers an alert based on the custom rule. 

Also, I've tried to create another detector using testing2 user, which runs on the same index but triggers an alert based on the different custom rules.

So, when I logged in using a different user, let's say the **admin** user, I can see all detectors, even though I have a mapping of the unique security role(s) and backend role(s). As I see, while creating detectors, there is no way we can filter the data, as we can only specify index or index patterns to run rules. But somehow I am unable to separate detectors and alerts generated using the same based on tenant users.

As per the expected behavior, the detector generated using a separate user and its relevant findings should only be visible to the corresponding users. I see no mention of detector ownership in this official documentation of [security analytics plugin](https://opensearch.org/docs/2.5/security-analytics) in opensearch 2.5x version. So, Is there any way, we can achieve this detector isolation?

Just to give context, I am trying to apply multi-tenancy concepts on the detectors the same way access control is available based on the security roles mapping.

**Comment by sbcd90** [comment]
hi @jinalp-fens , we need to explicitly enable `rbac` for the `security-analytics` plugin.

```
PUT /_cluster/settings
{
  "transient" : {
    "plugins.security_analytics.filter_by_backend_roles" : "true"
  }
}
```
& then the `multi-tenancy` concept will be enabled.
cc: @getsaurabh02

**Comment by jinalp-fens** [comment]
> hi @jinalp-fens , we need to explicitly enable `rbac` for the `security-analytics` plugin.
> 
> ```
> PUT /_cluster/settings
> {
>   "transient" : {
>     "plugins.security_analytics.filter_by_backend_roles" : "true"
>   }
> }
> ```
> 
> & then the `multi-tenancy` concept will be enabled. cc: @getsaurabh02

Thanks for the reply. Can you please provide the documentation for the same, as it would be helpful for referring?

Let's say I have all tenant data in one index and enabled this setting to show me only the corresponding tenant's detectors as per the backend role. But still, how can we run a detector on specific tenants' data, as there is no direct support for alias or index filtering in the security analytics plugin as a data source? Is there any roadmap for the same?
(Only indices and index patterns are supported as the data source, as of now for OpenSearch 2.6x )
