### ISSUE TITLE
[Refactor] XContent from common to core namespace

### ISSUE THREAD

**Issue by nknize** [opensearch-project/security-analytics#382]
XContent namespace refactor from common -> core is going to be merged to opensearch/2.x which will break the 2.x build.  This issue is for refactoring XContent imports from the `common` to `core` namespace after the core namespace change is merged.

Depends on https://github.com/opensearch-project/OpenSearch/pull/6470

**Comment by nknize** [comment]
https://github.com/opensearch-project/OpenSearch/pull/6470 merged

**Comment by nknize** [comment]
Ping! Anything to be done here?

**Comment by dblock** [comment]
@praveensameneni

**Comment by sbcd90** [comment]
this is completed by [
#389](https://github.com/opensearch-project/security-analytics/pull/389)
