### ISSUE TITLE
[FEATURE] Findings management layer in Security Analytics

### ISSUE THREAD

**Issue by eirsep** [opensearch-project/security-analytics#41]
**Is your feature request related to a problem?**
Security Analytics Plugin(SAP) detectors create monitors in Alerting plugin. If SAP creates a Document Level Monitors, these monitors can generate alerts and findings which are of interest to user. This issue focuses on the FINDINGS created by SAP owned monitors and how we can surface the findings to the user.

**What solution would you like?**
We would require an API in SAP to fetch findings based on detector id. This API would require SAP to make transport layer call to get findings based on the custom findings index from Alerting.

**Comment by eirsep** [comment]
@petardz  Can you post the request, response structure for API documentation

Would API end point be `/_plugins/_security_analytics/_detectors/<detector_id>/findings` or something else?

**Comment by petardz** [comment]
### GetFindings API

**_REQUEST:_**
```
GET /_plugins/_security_analytics/findings/_search?detectorId=12345
```
**_RESPONSE:_**
```
{
        "detectorId": "12345",
	"total_findings":2,
	"findings":[
		{
			"finding":{
				"id":"2b9663f4-ae77-4df8-b84f-688a0195723b",
				"related_doc_ids":[
					"5"
				],
				"monitor_id":"vmgJhoMBinvhwv0cEvth",
				"monitor_name":"TZbllyjvkd",
				"index":"sbwhrzgdlg",
				"queries":[
					{
						"id":"f1bff160-587b-4500-b60c-ab22c7abc652",
						"name":"3",
						"query":"test_field:\"us-west-2\"",
						"tags":[
							
						]
					}
				],
				"timestamp":1664401088804
			},
			"document_list":[
				{
					"index":"sbwhrzgdlg",
					"id":"5",
					"found":true,
					"document":"{\n            \"message\" : \"This is an error from IAD region\",\n            \"test_strict_date_time\" : \"2022-09-28T21:38:02.888Z\",\n            \"test_field\" : \"us-west-2\"\n        }"
				}
			]
		},
		{
			"finding":{
				"id":"f43a2701-0ef5-4931-8254-bdf510f73952",
				"related_doc_ids":[
					"1"
				],
				"monitor_id":"vmgJhoMBinvhwv0cEvth",
				"monitor_name":"TZbllyjvkd",
				"index":"sbwhrzgdlg",
				"queries":[
					{
						"id":"f1bff160-587b-4500-b60c-ab22c7abc652",
						"name":"3",
						"query":"test_field:\"us-west-2\"",
						"tags":[
							
						]
					}
				],
				"timestamp":1664401088746
			},
			"document_list":[
				{
					"index":"sbwhrzgdlg",
					"id":"1",
					"found":true,
					"document":"{\n            \"message\" : \"This is an error from IAD region\",\n            \"test_strict_date_time\" : \"2022-09-28T21:38:02.888Z\",\n            \"test_field\" : \"us-west-2\"\n        }"
				}
			]
		}
	]
}
```

**Comment by eirsep** [comment]
@getsaurabh02 @praveensameneni  @petardz 
As a user I would want a view findigs with following capabilities:
1. I would want to fetch all findings for ALL detectors i.e. `/_security_analytics/findings`
2.  Pass params in API to filter findings based on following criteria
- list of detector types
- list of detector ids
- time range
3. Limit number of findings to fetch
4. Sort based on field
