### ISSUE TITLE
[BUG] Missing Image mapping field

### ISSUE THREAD

**Issue by jiris245** [opensearch-project/security-analytics#410]
**What is the bug?**
There is no Image field item in the field mapping. 

**What is your host/environment?**
 - OS: Ubuntu
 - Version 22.04 LTS
 - Plugins:

**Do you have any screenshots?**
![image](https://user-images.githubusercontent.com/125290403/234030260-ad8e72f3-3ea0-4368-8ebf-757a083ef28b.png)

**Comment by praveensameneni** [comment]
Looking into the issue

**Comment by getsaurabh02** [comment]
@petardz to look into this

**Comment by petardz** [comment]
@jiris245 Mapping fixes will be pushed with this [PR](https://github.com/opensearch-project/security-analytics/pull/465/files#diff-d4e2659efc4a54d33e4219bebe95cd765e780af226d794a3ee03209238c76e51R439)

**Comment by amsiglan** [comment]
Fixed in PR #465
