### ISSUE TITLE
[BUG] One detector should be able to support multiple monitors

### ISSUE THREAD

**Issue by eirsep** [opensearch-project/security-analytics#42]
One rule might need multiple monitors
Detector model in index should roughly look like the following:

```
Detector {
List<MonitorConfig>
}

MonitorConfig {
    String monitorId
    String monitorType
    String alertIndex,
    String queryIndex,
    String findingsIndex
}
```

this way we can abstract out and not have any monitor info in the response..

**Comment by getsaurabh02** [comment]
@sbcd90 This is a plan to ensure that the ``Threat Detector`` in Security Analytics could abstract more than one ``Monitor`` on the Alerting side. The CRUD Detector APIs should ensure the update of the config file on the Security Analytics side are supporting the same.

**Comment by getsaurabh02** [comment]
@eirsep @petardz The Findings and Alerts API on the Security Analytics should assume that each detector can abstract more than one monitors, and hence the response should be clubbed and returned back to the client.

**Comment by raj-chak** [comment]
Here is what a sample response for Get Detector would look like after the change:
{
  "detector": {
    "type": "detector",
    "name": "xsQlrkpfDy",
    "detector_type": "WINDOWS",
    "user": null,
    "enabled": true,
    "enabled_time": 1663968045609,
    "schedule": {
      "period": {
        "interval": 5,
        "unit": "MINUTES"
      }
    },
    "inputs": [
      {
        "detector_input": {
          "description": "windows detector for security analytics",
          "indices": [
            "windows"
          ],
          "rules": []
        }
      }
    ],
    "last_update_time": 1663968045658,
    "monitors": [
      {
        "id": "qis5bIMBQ_24yELZcH7N",
        "type": "Doc_level_monitor",
        "alert_index": ".opensearch-sap-alerts-windows",
        "query_index": ".opensearch-sap-detectors-queries-windows",
        "findings_index": ".opensearch-sap-findings-windows"
      }
    ]
  }
}

**Comment by raj-chak** [comment]
We need to write ser/deser methods in MonitorConfig and also change Detector, GetDetectorResponse etc
