### ISSUE TITLE
packetbeat for DNS and sigma rules

### ISSUE THREAD

**Issue by mareban** [opensearch-project/security-analytics#429]
Hello,

We've tried hard to use the sap for threat detection and had some issues 
- we need to create an _index_template instead of template
- when remove detectors we need to cleanup some stuff

Now everything seems ok but to test sigma rules, we start by testing  simple ones like "Wannacry killswitch Domain" or "DNS Query to External Service Interaction Domains" making the dns queries and nothing is triggered !

The query field in the sigma rule was mapped automatically, the field exist in the indices but  no alert was generated :-( !

Do we miss something ? We are hoping all the other rules will work out of the box

Thanks for your help

**Comment by mareban** [comment]
Hello,

Thx for your reply.

for detector : 

{
  "took": 2,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": {
      "value": 1,
      "relation": "eq"
    },
    "max_score": 1,
    "hits": [
      {
        "_index": ".opensearch-sap-detectors-config",
        "_id": "VSt27YcBWxop2mCm87J6",
        "_score": 1,
        "_source": {
          "detector": {
            "type": "detector",
            "name": "DNS-Sigma",
            "detector_type": "dns",
            "user": {
              "name": "admin",
              "backend_roles": [
                "admin"
              ],
              "roles": [
                "own_index",
                "all_access"
              ],
              "custom_attribute_names": [],
              "user_requested_tenant": "itops_tenant"
            },
            "enabled": true,
            "enabled_time": 1683316186526,
            "schedule": {
              "period": {
                "interval": 5,
                "unit": "MINUTES"
              }
            },
            "inputs": [
              {
                "detector_input": {
                  "description": "",
                  "indices": [
                    "packetbeat-*"
                  ],
                  "custom_rules": [
                    {
                      "id": "c9Vg-4cBWpSC3z_F4BaJ"
                    }
                  ],
                  "pre_packaged_rules": [
                    {
                      "id": "3eaf6218-3bed-4d8a-8707-274096f12a18"
                    },
                    {
                      "id": "8ae51330-899c-4641-8125-e39f2e07da72"
                    },
                    {
                      "id": "c64c5175-5189-431b-a55e-6d9882158251"
                    },
                    {
                      "id": "4153a907-2451-4e4f-a578-c52bb6881432"
                    },
                    {
                      "id": "b593fd50-7335-4682-a36c-4edcb68e4641"
                    },
                    {
                      "id": "2975af79-28c4-4d2f-a951-9095f229df29"
                    },
                    {
                      "id": "f0a8cedc-1d22-4453-9c44-8d9f4ebd5d35"
                    },
                    {
                      "id": "b4163085-4001-46a3-a79a-55d8bbbc7a3a"
                    },
                    {
                      "id": "44ae5117-9c44-40cf-9c7c-7edad385ca70"
                    },
                    {
                      "id": "0f6c1bf5-70a5-4963-aef9-aab1eefb50bd"
                    },
                    {
                      "id": "aff715fa-4dd5-497a-8db3-910bea555566"
                    },
                    {
                      "id": "1ec4b281-aa65-46a2-bdae-5fd830ed914e"
                    }
                  ]
                }
              }
            ],
            "triggers": [
              {
                "id": "BCt27YcBWxop2mCmnVye",
                "name": "DNS-Sigma-Alert",
                "severity": "2",
                "types": [
                  "dns"
                ],
                "ids": [],
                "sev_levels": [],
                "tags": [],
                "actions": [
                  {
                    "id": "",
                    "name": "Triggered alert condition: DNS-Sigma-Alert - Severity: 1 (Highest) - Threat detector: DNS-Sigma",
                    "destination_id": "ZrvXmIYBpLf1SzgMrVYh",
                    "message_template": {
                      "source": """Triggered alert condition: DNS-Sigma-Alert
Severity: 1 (Highest)
Threat detector: DNS-Sigma
Description: 
Detector data sources:
	packetbeat*""",
                      "lang": "mustache"
                    },
                    "throttle_enabled": false,
                    "subject_template": {
                      "source": "Triggered alert condition: DNS-Sigma-Alert - Severity: 1 (Highest) - Threat detector: DNS-Sigma",
                      "lang": "mustache"
                    },
                    "throttle": {
                      "value": 10,
                      "unit": "MINUTES"
                    }
                  }
                ]
              }
            ],
            "last_update_time": 1683576844509,
            "monitor_id": [
              "BSt27YcBWxop2mCmnVzA"
            ],
            "bucket_monitor_id_rule_id": {
              "-1": "BSt27YcBWxop2mCmnVzA"
            },
            "rule_topic_index": ".opensearch-sap-dns-detectors-queries",
            "alert_index": ".opensearch-sap-dns-alerts",
            "alert_history_index": ".opensearch-sap-dns-alerts-history",
            "alert_history_index_pattern": "<.opensearch-sap-dns-alerts-history-{now/d}-1>",
            "findings_index": ".opensearch-sap-dns-findings",
            "findings_index_pattern": "<.opensearch-sap-dns-findings-{now/d}-1>"
          }
        }
      }
    ]
  }
}


For the logtype "dns" : 

{
  "took": 4,
  "timed_out": false,
  "_shards": {
    "total": 8,
    "successful": 8,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": {
      "value": 373,
      "relation": "eq"
    },
    "max_score": 1,
    "hits": [
      {
        "_index": ".opensearch-sap-dns-detectors-queries-000001",
        "_id": "3eaf6218-3bed-4d8a-8707-274096f12a18_packetbeat-2023.04.28_BSt27YcBWxop2mCmnVzA",
        "_score": 1,
        "_source": {
          "query": {
            "query_string": {
              "query": """(dns-question-name_packetbeat-2023.04.28_BSt27YcBWxop2mCmnVzA: "ifferfsodp9ifjaposdfjhgosurijfaewrwergwea.testing") OR (dns-question-name_packetbeat-2023.04.28_BSt27YcBWxop2mCmnVzA: "ifferfsodp9ifjaposdfjhgosurijfaewrwergwea.test") OR (dns-question-name_packetbeat-2023.04.28_BSt27YcBWxop2mCmnVzA: "ifferfsodp9ifjaposdfjhgosurijfaewrwergwea.com") OR (dns-question-name_packetbeat-2023.04.28_BSt27YcBWxop2mCmnVzA: "ayylmaotjhsstasdfasdfasdfasdfasdfasdfasdf.com") OR (dns-question-name_packetbeat-2023.04.28_BSt27YcBWxop2mCmnVzA: "iuqssfsodp9ifjaposdfjhgosurijfaewrwergwea.com")"""
            }
          },
          "monitor_id": "BSt27YcBWxop2mCmnVzA",
          "index": "packetbeat-2023.04.28"
        }
      },
      {
        "_index": ".opensearch-sap-dns-detectors-queries-000001",
        "_id": "8ae51330-899c-4641-8125-e39f2e07da72_packetbeat-2023.04.28_BSt27YcBWxop2mCmnVzA",
        "_score": 1,
        "_source": {
          "query": {
            "query_string": {
              "query": """(dns-answers-type_packetbeat-2023.04.28_BSt27YcBWxop2mCmnVzA: "TXT") AND ((answer: *IEX*) OR (answer: *Invoke\-Expression*) OR (answer: *cmd.exe*))"""
            }
          },
          "monitor_id": "BSt27YcBWxop2mCmnVzA",
          "index": "packetbeat-2023.04.28"
        }
      },
      {
        "_index": ".opensearch-sap-dns-detectors-queries-000001",
        "_id": "c64c5175-5189-431b-a55e-6d9882158251_packetbeat-2023.04.28_BSt27YcBWxop2mCmnVzA",
        "_score": 1,
        "_source": {
          "query": {
            "query_string": {
              "query": "dns-question-name_packetbeat-2023.04.28_BSt27YcBWxop2mCmnVzA: \"api.telegram.org\""
            }
          },
          "monitor_id": "BSt27YcBWxop2mCmnVzA",
          "index": "packetbeat-2023.04.28"
        }
      },
      {
        "_index": ".opensearch-sap-dns-detectors-queries-000001",
        "_id": "4153a907-2451-4e4f-a578-c52bb6881432_packetbeat-2023.04.28_BSt27YcBWxop2mCmnVzA",
        "_score": 1,
        "_source": {
          "query": {
            "query_string": {
              "query": """dns-question-name_packetbeat-2023.04.28_BSt27YcBWxop2mCmnVzA: *\=\=.*"""
            }
          },
          "monitor_id": "BSt27YcBWxop2mCmnVzA",
          "index": "packetbeat-2023.04.28"
        }
      },
      {
        "_index": ".opensearch-sap-dns-detectors-queries-000001",
        "_id": "b593fd50-7335-4682-a36c-4edcb68e4641_packetbeat-2023.04.28_BSt27YcBWxop2mCmnVzA",
        "_score": 1,
        "_source": {
          "query": {
            "query_string": {
              "query": """(dns-question-name_packetbeat-2023.04.28_BSt27YcBWxop2mCmnVzA: *pool.minexmr.com*) OR (dns-question-name_packetbeat-2023.04.28_BSt27YcBWxop2mCmnVzA: *fr.minexmr.com*) OR (dns-question-name_packetbeat-2023.04.28_BSt27YcBWxop2mCmnVzA: *de.minexmr.com*) OR (dns-question-name_packetbeat-2023.04.28_BSt27YcBWxop2mCmnVzA: *sg.minexmr.com*) OR (dns-question-name_packetbeat-2023.04.28_BSt27YcBWxop2mCmnVzA: *ca.minexmr.com*) OR (dns-question-name_packetbeat-2023.04.28_BSt27YcBWxop2mCmnVzA: *us\-west.minexmr.com*) OR (dns-question-name_packetbeat-2023.04.28_BSt27YcBWxop2mCmnVzA: *pool.supportxmr.com*) OR (dns-question-name_packetbeat-2023.04.28_BSt27YcBWxop2mCmnVzA: *mine.c3pool.com*) OR (dns-question-name_packetbeat-2023.04.28_BSt27YcBWxop2mCmnVzA: *xmr\-eu1.nanopool.org*) OR (dns-question-name_packetbeat-2023.04.28_BSt27YcBWxop2mCmnVzA: *xmr\-eu2.nanopool.org*) OR (dns-question-name_packetbeat-2023.04.28_BSt27YcBWxop2mCmnVzA: *xmr\-us\-east1.nanopool.org*) OR (dns-question-name_packetbeat-2023.04.28_BSt27YcBWxop2mCmnVzA: *xmr\-us\-west1.nanopool.org*) OR (dns-question-name_packetbeat-2023.04.28_BSt27YcBWxop2mCmnVzA: *xmr\-asia1.nanopool.org*) OR (dns-question-name_packetbeat-2023.04.28_BSt27YcBWxop2mCmnVzA: *xmr\-jp1.nanopool.org*) OR (dns-question-name_packetbeat-2023.04.28_BSt27YcBWxop2mCmnVzA: *xmr\-au1.nanopool.org*) OR (dns-question-name_packetbeat-2023.04.28_BSt27YcBWxop2mCmnVzA: *xmr.2miners.com*) OR (dns-question-name_packetbeat-2023.04.28_BSt27YcBWxop2mCmnVzA: *xmr.hashcity.org*) OR (dns-question-name_packetbeat-2023.04.28_BSt27YcBWxop2mCmnVzA: *xmr.f2pool.com*) OR (dns-question-name_packetbeat-2023.04.28_BSt27YcBWxop2mCmnVzA: *xmrpool.eu*) OR (dns-question-name_packetbeat-2023.04.28_BSt27YcBWxop2mCmnVzA: *pool.hashvault.pro*)"""
            }
          },
          "monitor_id": "BSt27YcBWxop2mCmnVzA",
          "index": "packetbeat-2023.04.28"
        }
      },
      {
        "_index": ".opensearch-sap-dns-detectors-queries-000001",
        "_id": "2975af79-28c4-4d2f-a951-9095f229df29_packetbeat-2023.04.28_BSt27YcBWxop2mCmnVzA",
        "_score": 1,
        "_source": {
          "query": {
            "query_string": {
              "query": "((dns-question-name_packetbeat-2023.04.28_BSt27YcBWxop2mCmnVzA: aaa.stage.*) OR (dns-question-name_packetbeat-2023.04.28_BSt27YcBWxop2mCmnVzA: post.1*)) OR (dns-question-name_packetbeat-2023.04.28_BSt27YcBWxop2mCmnVzA: *.stage.123456.*)"
            }
          },
          "monitor_id": "BSt27YcBWxop2mCmnVzA",
          "index": "packetbeat-2023.04.28"
        }
      },
      {
        "_index": ".opensearch-sap-dns-detectors-queries-000001",
        "_id": "f0a8cedc-1d22-4453-9c44-8d9f4ebd5d35_packetbeat-2023.04.28_BSt27YcBWxop2mCmnVzA",
        "_score": 1,
        "_source": {
          "query": {
            "query_string": {
              "query": "dns-answers-type_packetbeat-2023.04.28_BSt27YcBWxop2mCmnVzA: \"TXT\""
            }
          },
          "monitor_id": "BSt27YcBWxop2mCmnVzA",
          "index": "packetbeat-2023.04.28"
        }
      },
      {
        "_index": ".opensearch-sap-dns-detectors-queries-000001",
        "_id": "b4163085-4001-46a3-a79a-55d8bbbc7a3a_packetbeat-2023.04.28_BSt27YcBWxop2mCmnVzA",
        "_score": 1,
        "_source": {
          "query": {
            "query_string": {
              "query": "dns-question-name_packetbeat-2023.04.28_BSt27YcBWxop2mCmnVzA: *"
            }
          },
          "monitor_id": "BSt27YcBWxop2mCmnVzA",
          "index": "packetbeat-2023.04.28"
        }
      },
      {
        "_index": ".opensearch-sap-dns-detectors-queries-000001",
        "_id": "44ae5117-9c44-40cf-9c7c-7edad385ca70_packetbeat-2023.04.28_BSt27YcBWxop2mCmnVzA",
        "_score": 1,
        "_source": {
          "query": {
            "query_string": {
              "query": "dns-answers-type_packetbeat-2023.04.28_BSt27YcBWxop2mCmnVzA: \"NULL\""
            }
          },
          "monitor_id": "BSt27YcBWxop2mCmnVzA",
          "index": "packetbeat-2023.04.28"
        }
      },
      {
        "_index": ".opensearch-sap-dns-detectors-queries-000001",
        "_id": "0f6c1bf5-70a5-4963-aef9-aab1eefb50bd_packetbeat-2023.04.28_BSt27YcBWxop2mCmnVzA",
        "_score": 1,
        "_source": {
          "query": {
            "query_string": {
              "query": "dns-question-name_packetbeat-2023.04.28_BSt27YcBWxop2mCmnVzA: *"
            }
          },
          "monitor_id": "BSt27YcBWxop2mCmnVzA",
          "index": "packetbeat-2023.04.28"
        }
      }
    ]
  }
}

Weird, when we create the detector, we use "packetbeat-*" as datasource, and schedule of 5 minutes !

Does that mean only index "packetbeat-2023.04.28" is used in the search and not the last index ?

In fact we have 13 DNS rules with 1 custom rules for info.
 

Maybe we have to clean other things :-( ?


Thanks for your help.

PS : we have all these indices since the creation of the detector

green open .opensearch-sap-dns-detectors-queries-000007 QyKhlLzhTLu4TGXD8-MP9w 1 1 49   195 669.8kb 356.9kb
green open .opensearch-sap-dns-detectors-queries-000008 yLY3kPadQpKCkqypXEKuwg 1 1 26   442 721.9kb 465.1kb
green open .opensearch-sap-dns-detectors-queries-000005 13Altd4sQqWdzCo80w6Hqg 1 1 52  1664   3.1mb   1.5mb
green open .opensearch-sap-dns-detectors-queries-000006 s358Es7wQ-y3dSbu9NpGDg 1 1 12     0   1.2mb 637.7kb
green open .opensearch-sap-dns-detectors-queries-000003 A-NNmzkpSxukjP3NLyXRAQ 1 1 52  2912   4.5mb   2.2mb
green open .opensearch-sap-dns-detectors-queries-000004 yBDOydCHQOOjSB1PKSujbQ 1 1 65  2080   3.9mb   1.9mb
green open .opensearch-sap-dns-detectors-queries-000001 NR7wYyTBSgiuqU_HTNBDBQ 1 1 65 46200  46.6mb    25mb
green open .opensearch-sap-dns-detectors-queries-000002 2X7i5W0CS2aLiXYQqPFBRQ 1 1 52  2912   4.5mb   2.3mb

**Comment by sbcd90** [comment]
hi @mareban , could you also post a sample document from the index `packetbeat-*` so that i can check if it generates a finding?

**Comment by mareban** [comment]
Hi, 

Just for info, we have these kind of errors in our logs :

2023-05-10T12:00:51,419][WARN ][o.o.a.DocumentLevelMonitorRunner] [opnscluster-n1] Failed to run for shard 11. Error: For input string: "null"
[2023-05-10T12:00:51,419][WARN ][o.o.a.DocumentLevelMonitorRunner] [opnscluster-n1] Failed to run for shard 12. Error: For input string: "null"
[2023-05-10T12:00:51,419][WARN ][o.o.a.DocumentLevelMonitorRunner] [opnscluster-n1] Failed to run for shard 13. Error: For input string: "null"
[2023-05-10T12:00:51,419][WARN ][o.o.a.DocumentLevelMonitorRunner] [opnscluster-n1] Failed to run for shard 14. Error: For input string: "null"
[2023-05-10T12:00:51,419][WARN ][o.o.a.DocumentLevelMonitorRunner] [opnscluster-n1] Failed to run for shard 15. Error: For input string: "null"

I don't know if it is related ?

Do we have something to troubleshoot security analytics plugin please ?


Thanks for your help.

**Comment by sbcd90** [comment]
hi @mareban , i used the `2.7.0` version to generate an alert successfully for your scenario.
here are the steps i followed.

- Create a custom dns rule

```
id: B9sxCIgBQ4gND99ySmlh
logsource:
  product: dns
title: Telegram Bot API Request
description: >-
  Detects suspicious DNS queries to api.telegram.org used by Telegram Bots of
  any kind
tags:
  - attack.command_and_control
  - attack.t1102.002
falsepositives:
  - Legitimate use of Telegram bots in the company
level: medium
status: experimental
references:
  - 'https://core.telegram.org/bots/faq'
  - >-
    https://researchcenter.paloaltonetworks.com/2018/03/unit42-telerat-another-android-trojan-leveraging-telegrams-bot-api-to-target-iranian-users/
  - >-
    https://blog.malwarebytes.com/threat-analysis/2016/11/telecrypt-the-ransomware-abusing-telegram-api-defeated/
  - >-
    https://www.welivesecurity.com/2016/12/13/rise-telebots-analyzing-disruptive-killdisk-attacks/
author: Florian Roth
detection:
  selection:
    query: onedscolprdeus12.eastus.cloudapp.azure.com
  condition: selection
```

- Create a detector using the custom rule.

```
POST /_plugins/_security_analytics/detectors
{
  "type": "detector",
  "schedule": {
    "period": {
      "unit": "MINUTES",
      "interval": 1
    }
  },
  "enabled": true,
  "inputs": [
    {
      "detector_input": {
        "indices": ["dns_logs_real"],
        "description": "dns logs detector for security analytics",
        "custom_rules": [
          {
            "id": "B9sxCIgBQ4gND99ySmlh"
          }
        ]
      }
    }
  ],
  "detector_type": "dns",
  "name": "dns-detector",
  "triggers": [
    {
      "actions": [],
      "ids": [],
      "id": "wf8XLYYBKCcJpfRF9CvJ",
      "types": [
        "dns"
      ],
      "name": "test-trigger",
      "tags": [],
      "severity": "1",
      "sev_levels": []
    }
  ]
}
```
![image](https://github.com/opensearch-project/security-analytics/assets/617607/97081f0c-834d-4508-a46a-3ca71d218d13)

- Ingest the packetbeat logs you shared.

```
PUT /dns_logs_real/_doc/2?refresh
{
  "@timestamp": "2023-05-08T05:38:39.629Z",
  "@metadata": {
    "beat": "packetbeat",
    "type": "_doc",
    "version": "7.10.2"
  },
  "server": {
    "ip": "10.1.1.153",
    "port": 53,
    "bytes": 87
  },
  "related": {
    "ip": [
      "10.1.2.4",
      "10.1.1.153",
      "20.42.73.27"
    ]
  },
  "resource": "onedscolprdeus12.eastus.cloudapp.azure.com",
  "destination": {
    "ip": "10.1.1.153",
    "port": 53,
    "bytes": 87
  },
  "query": "class IN, type A, onedscolprdeus12.eastus.cloudapp.azure.com",
  "ecs": {
    "version": "1.5.0"
  },
  "event": {
    "type": [
      "connection",
      "protocol"
    ],
    "kind": "event",
    "dataset": "dns",
    "duration": 223000,
    "start": "2023-05-08T05:38:39.629Z",
    "end": "2023-05-08T05:38:39.629Z",
    "category": [
      "network_traffic",
      "network"
    ]
  },
  "dns": {
    "opt": {
      "do": true,
      "version": "0",
      "udp_size": 4000,
      "ext_rcode": "NOERROR"
    },
    "response_code": "NOERROR",
    "header_flags": [
      "RD",
      "RA",
      "DO"
    ],
    "answers": [
      {
        "data": "20.42.73.27",
        "name": "onedscolprdeus12.eastus.cloudapp.azure.com",
        "type": "A",
        "class": "IN",
        "ttl": "0"
      }
    ],
    "id": 2859,
    "op_code": "QUERY",
    "additionals_count": 0,
    "type": "answer",
    "question": {
      "class": "IN",
      "etld_plus_one": "azure.com",
      "registered_domain": "azure.com",
      "top_level_domain": "com",
      "subdomain": "onedscolprdeus12.eastus.cloudapp",
      "name": "onedscolprdeus12.eastus.cloudapp.azure.com",
      "type": "A"
    },
    "answers_count": 1,
    "authorities_count": 0,
    "flags": {
      "authoritative": false,
      "truncated_response": false,
      "recursion_desired": true,
      "recursion_available": true,
      "authentic_data": false,
      "checking_disabled": false
    },
    "resolved_ip": [
      "20.42.73.27"
    ]
  },
  "source": {
    "bytes": 71,
    "ip": "10.1.2.4",
    "port": 61172
  },
  "agent": {
    "name": "DOMDNS2",
    "type": "packetbeat",
    "version": "7.10.2",
    "hostname": "DOMDNS2",
    "ephemeral_id": "48470c46-c59c-47fa-bb2b-82880f97622b",
    "id": "de320f94-e3ce-44e5-9fc4-1379e0fe070b"
  },
  "status": "OK",
  "network": {
    "protocol": "dns",
    "direction": "inbound",
    "community_id": "1:w0uFtIuIJzCzrQjWc72X3dcr8Vg=",
    "bytes": 158,
    "type": "ipv4",
    "transport": "udp"
  },
  "client": {
    "port": 61172,
    "bytes": 71,
    "ip": "10.1.2.4"
  },
  "type": "dns",
  "method": "QUERY",
  "host": {
    "mac": [
      "00:53:23:97:88:ab"
    ],
    "name": "DOMDNS2",
    "hostname": "DOMDNS2",
    "architecture": "x86_64",
    "os": {
      "build": "17763.4252",
      "platform": "windows",
      "version": "10.0",
      "family": "windows",
      "name": "Windows Server 2019 Standard",
      "kernel": "10.0.17763.4252 (WinBuild.160101.0800)"
    },
    "id": "364f38b9-a0bb-44bd-ae59-a81c4e7ff5e6",
    "ip": [
      "10.1.1.153"
    ]
  },
  "ip_resolved": "20.42.73.27",
  "rangeType": "public",
  "location_properties": {
    "lat": 37.751,
    "lon": -97.822
  },
  "location_string": "37.751,-97.822",
  "geoip.location": [
    -97.822,
    37.751
  ],
  "latitude": 37.751,
  "longitude": -97.822,
  "country_code3": null,
  "country": "US",
  "country_name": "United States",
  "area": null,
  "region": null,
  "city": null
}
```

i see the findings generated.

![image](https://github.com/opensearch-project/security-analytics/assets/617607/f484d6eb-a5e8-452e-8ba4-866ffbfb3ebb)

**Comment by mareban** [comment]
Hi,

Thanks for your reply.

We don't want to create custom rules but use the default rules provided :-) !

For the datasource , can we specify a pattern like packetbeat-* (packetbeat-2023.05.01, 02, 03, ..  and so on )?

Do we have to use dev tools instead of the GUI to create a custom  rule ?

We are planning to upgrade the cluster next month, but do we have to be in 2.7.0 to fix our problem ?


Thanks for your help.

**Comment by mareban** [comment]
Hi ,


Is there a way to troubleshoot the issue please, like a debug mode ?

We would like to avoid to reinstall Opensearch or to restart from scratch, and avoid to upgrade too (dependencies supported in 2.6 at this time)  if it is possible  ?

Thanks for your help.

**Comment by sbcd90** [comment]
hi mareban@, there is no pre-packaged rule which has `query.question.name` == `onedscolprdeus12.eastus.cloudapp.azure.com`. so, a custom rule needs to be created to match the particular log record you shared.

there is also a bug fix in `2.7` which is needed for fields with `dots(.)`.
https://github.com/opensearch-project/alerting/pull/845

**Comment by mareban** [comment]
Hello,

Thanks very much for your help.  So we will upgrade to 2.7 soon.

Best regards

**Comment by getsaurabh02** [comment]
Fix is available in the latest release.

**Comment by mareban** [comment]
Hi,

Thx for reply :-) ! Which release 2.7 or 2.8 ? If it's 2.8 can we update from 2.6 to 2.8 or do we need to upgrade to 2.7 first ?

Thanks for your help.

**Comment by sbcd90** [comment]
hi @mareban , update can be done from `2.6` to `2.8`.

**Comment by mareban** [comment]
Hi

Thank you very much for your help :-), we'll try !

BR
