### ISSUE TITLE
[BUG] Mapper not found: [linux]

### ISSUE THREAD

**Issue by paasi6666** [opensearch-project/security-analytics#432]
**What is the bug?**
When defining a new detector and selecting the "System Logs" type, the "Configure field mapping" are empty.

**How can one reproduce the bug?**
1. Go to Security Analytics>Detectors>Create detector
2. Select any index
3. Click on 'System logs':

![image](https://github.com/opensearch-project/security-analytics-dashboards-plugin/assets/26493612/6cac73d1-3cfe-42a4-88c6-7a64781e8748)

5. See that 'Configure field mapping' is empty
6. When following the link (mappings/view?indexName=index_*&ruleTopic=linux), following message is displayed:

`{"ok":false,"error":"[illegal_argument_exception] Mapper not found: [linux]"}`

**What is the expected behavior?**
Like the other types (Azure logs for example):

![image](https://github.com/opensearch-project/security-analytics-dashboards-plugin/assets/26493612/af2e09e5-0bc4-46e5-a54c-b3f7c38dbdeb)

Also, when following the link:
`{"ok":true,"response":{"properties":{},"unmapped_index_fields":`

**What is your host/environment?**
- OS: Centos7
- Opensearch Version: 2.7.0
- Opensearch-Dashboards Version: 2.7.0

**Comment by sbcd90** [comment]
will look into it.

**Comment by sbcd90** [comment]
thanks for creating the issue. created a pr to fix it.

**Comment by dsek** [comment]
this is the same problem as described weeks ago via https://github.com/opensearch-project/security-analytics/pull/320

**Comment by Aloush-ha** [comment]
Hi @dsek 
we are all together having the same problem, but how can we push to solve it.
I saw that your PR is not merged until know

**Comment by dsek** [comment]
yeah ... i've no idea ... maybe somebody of the security-analytics team may take care of it.

<sarcasm>
i do really understand that handling this really complicated pull request takes so much time ...
</sarcasm>

**Comment by Aloush-ha** [comment]
thank you @sbcd90

**Comment by paasi6666** [comment]
Thanks @sbcd90

**Comment by getsaurabh02** [comment]
Fix is available in 2.8 release

**Comment by Aloush-ha** [comment]
Hi @sbcd90
I checked the new Version 2.8, and I realized something, maybe you can explain it to us.
![Screenshot 2023-06-26 120416](https://github.com/opensearch-project/security-analytics/assets/41262620/31d48fdc-d79c-4acc-ae27-bc7beb853960)

As you can see, in System logs there is audit field, and some fields that not compatible with Linux syslog
can you explain to me, which field in Linux syslog can pointed to rsa-web-remote_domain or process-working_directory !?
Which field is the message ?

should I open another Issue for that?

thank you

**Comment by paasi6666** [comment]
Hi @Aloush-ha 

I think you should open a new issue since this one is closed.
