### ISSUE TITLE
[FEATURE] Mappings View and apply flow APIs

### ISSUE THREAD

**Issue by petardz** [opensearch-project/security-analytics#44]
**Is your feature request related to a problem?**

Frontend needs capability to display a view of field mappings for a given **_index_name_** and _**_rule_topic_.**_ That view would have list of fields from index with corresponding aliases from template alias mappings. User would be able to edit given View of mappings and apply them on index. Edit would allow picking different alias for field from a list of returned aliases. 
**CreateIndexMappings** API currently applies predefined alias mappings designated by **_rule_topic_** parameter. We need to extend capability of API to accept alias mappings from user too.

**What solution would you like?**
Implement new API/Action GetMappingsViewAction. 

For a given **_index_name_** parameter, returns list of index fields and proposed aliases which are defined in template alias mappings file, designated by **rule_topic** parameter.
Example:

**REQUEST:**
``` 
GET _plugins/_security_analytics/mappings/view?index_name=sample_index&rule_topic=netflow
```
**RESPONSE:**
```
{
  "properties": {
    "source.ip": {
      "type": "alias",
      "path": "netflow.source_ipv4_address"
    },
    "source.port": {
      "type": "alias",
      "path": "netflow.source_transport_port"
    },
    "destination.ip": {
      "type": "alias",
      "path": "netflow.destination_ipv4_address"
    },
    "destination.port": {
      "type": "alias",
      "path": "netflow.destination_transport_port"
    },
    "http.request.method": {
      "type": "alias",
      "path": "netflow.http_request_method"
    },
    "http.response.status_code": {
      "type": "alias",
      "path": "netflow.http_status_code"
    }
  },
  "unmapped_index_fields": [
      "src_client_ip",
      "user_source_ip"
  ],
  "unmapped_field_aliases": [
      "source_ip",
      "client_ip"
  }
}
```
Response will include following:
| property | description |
| --- | --- |
| **_properties_** | applicable alias mappings to a given index. |
| **_unmapped_index_fields_** | list of fields in given index for which there are no found alias mappings |
| **_unmapped_field_aliases_** | list of aliases which path didn't match any field in given index |
### 
**_CreateIndexMappings API changes_**
###
Currently this API accepts only **_index_name_**, **_rule_topic_** and **_partial_** parameters. New parameter **_alias_mappings_** will contain json alias mappings provided by user. These mappings will be applied to index, instead of **_rule_topic_** ones. Example:

**REQUEST:**
```
POST _plugins/_security_analytics/mappings
{
   "index_name": "sample_index",
   "alias_mappings": {
        "properties": {
           "source.ip": {
              "type": "alias",
              "path": "netflow.source_ipv4_address"
           },
           "source.port": {
              "type": "alias",
              "path": "netflow.source_transport_port"
           }
       }
   }
}
```
**RESPONSE:**
```
{
   "acknowledged": true
} 
```

**Do you have any additional context?**

**Comment by getsaurabh02** [comment]
The response for the ``view`` API can also provide the list of unmapped ``fields`` from index and ``field_aliases`` from the template. This will allow dashboard to populate the unmapped fields & aliases under dropped down options, which the system could not map automatically. Thus customers should to be able to map custom/alternative fields accordingly. 

Such as:


```
{
  "properties": {
    "source.ip": {
      "type": "alias",
      "path": "netflow.source_ipv4_address"
    },
    "source.port": {
      "type": "alias",
      "path": "netflow.source_transport_port"
    },
    "destination.ip": {
      "type": "alias",
      "path": "netflow.destination_ipv4_address"
    },
    "destination.port": {
      "type": "alias",
      "path": "netflow.destination_transport_port"
    },
    "http.request.method": {
      "type": "alias",
      "path": "netflow.http_request_method"
    },
    "http.response.status_code": {
      "type": "alias",
      "path": "netflow.http_status_code"
    }
  }
  "unmapped_index_fields": {
      "src_client_ip",
      "user_source_ip"
  }
  "unmapped_field_aliases": {
      "source_ip",
      "client_ip"
  }
}

```

**Comment by getsaurabh02** [comment]
The ``CreateIndexMappings`` implementation should allow some basic pre-validation on field availability in index and non-duplicate field aliases being applied.

**Comment by amsiglan** [comment]
What values does the rule_topic query param support? Can you list the string names for the topics?
