### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by nknize** [opensearch-project/security-analytics#508]
**What is the bug?**
Build fails with some latest namespace and library refactoring from core (e.g., https://github.com/opensearch-project/OpenSearch/pull/9005). This was caught by the [compatibility checker](https://github.com/opensearch-project/OpenSearch/actions/runs/5742101583/job/15563536027?pr=9073#step:3:2172) on https://github.com/opensearch-project/OpenSearch/pull/9073.

**How can one reproduce the bug?**
Build with latest Core SNAPSHOT

**What is the expected behavior?**
Build passes

**Do you have any screenshots?**
```
> Task :checkCompatibility

/tmp/groovy-generated-tmpdir-4501804200968858888/src/main/java/org/opensearch/securityanalytics/SecurityAnalyticsPlugin.java:25: error: package org.opensearch.common.component does not exist
import org.opensearch.common.component.LifecycleComponent;
                                      ^
/tmp/groovy-generated-tmpdir-4501804200968858888/src/main/java/org/opensearch/securityanalytics/SecurityAnalyticsPlugin.java:26: error: cannot find symbol
import org.opensearch.common.io.stream.NamedWriteableRegistry;
                                      ^
  symbol:   class NamedWriteableRegistry
  location: package org.opensearch.common.io.stream
/tmp/groovy-generated-tmpdir-4501804200968858888/src/main/java/org/opensearch/securityanalytics/util/CorrelationIndices.java:27: error: cannot find symbol
import org.opensearch.rest.RestStatus;
```

**Do you have any additional context?**
[#5910](https://github.com/opensearch-project/OpenSearch/issues/5910)

**Comment by amsiglan** [comment]
Closed by PR #510
