### ISSUE TITLE
Support for fetching rule data in detector's trigger notification message in CTX variable

### ISSUE THREAD

**Issue by eirsep** [opensearch-project/security-analytics#514]
Currently we only support Detector's trigger
ctx.detector containing {_id=qVGldIkB0UfzAtaegDPc, _version=1, name=test-detector, enabled=true}

Customer is unable to see information about which Sigma RULE triggered the alert notification.

**Comment by eirsep** [comment]
We need to support adding tags in monitor, query, alert in Alerting Plugin, which can help us populate info like rule, detector id etc in Alerting resources and make them available in alert notification also.

**Comment by praveensameneni** [comment]
@AWSHurneyt , can you please share the PR to include the message from ctx variable

**Comment by AWSHurneyt** [comment]
Implemented this in PR https://github.com/opensearch-project/alerting/pull/1450

**Comment by engechas** [comment]
Closing as completed by #1450 in alerting
