### ISSUE TITLE
[Refactor]Fix from upstream core.action changes

### ISSUE THREAD

**Issue by YANG-DB** [opensearch-project/security-analytics#516]
**Is your feature request related to a problem?**
Import changes from main due to: https://github.com/opensearch-project/OpenSearch/pull/9082

**What solution would you like?**
Fix non-compiling issues - import updates

**Do you have any additional context?**
- https://github.com/opensearch-project/OpenSearch/pull/9082

**Comment by sbcd90** [comment]
closing as pr merged already.
