### ISSUE TITLE
[FEATURE] GetAlerts API

### ISSUE THREAD

**Issue by petardz** [opensearch-project/security-analytics#55]
**Is your feature request related to a problem?**
SAP needs API to fetch all Alerts for a Detector

**What solution would you like?**
Add GetAlerts API to fetch all Alerts related to a Detector

REQUEST:

Params:
| param | description |
| --- | --- |
| **_detectorId_**  (OPTIONAL) | ID of Detector to fetch alertings for. This param is required if **_detectorType_** is **null** |
| **_detectorType_**  (OPTIONAL) | Type of Detector to fetch alertings for. This param is required if **_detectorId_** is **null** |
| **_severityLevel_**  (OPTIONAL) | Used to filter by Alert SeverityLevel  |
| **_alertState_**. (OPTIONAL) | Used to filter by Alert State. Possible values: ACTIVE, ACKNOWLEDGED, COMPLETED, ERROR, DELETED |
| **_sortString_**. (OPTIONAL) | This field specifies which string the Alerting plugin uses to sort the alerts |
| **_sortOrder_**. (OPTIONAL) | The order to sort the list of findings, either ascending or descending |
| **_missing_**. (OPTIONAL) | list of fields in given index for which there are no found alias mappings |
| **_size_**. (OPTIONAL) | An optional limit for the maximum number of results returned in the response |
| **_startIndex_**. (OPTIONAL) | The pagination indicator |
| **_searchString_**. (OPTIONAL) | The alert attribute you want returned in the search |

```
GET /_plugins/_security_analytics/alerts?detectorType=network
```

RESPONSE:
```
{
	"alerts":[
		{
			"detector_id":"detector_12345",
			"id":"alert_id_1",
			"version":-3,
			"schema_version":0,
			"trigger_id":"trigger_id_1",
			"trigger_name":"my_trigger",
			"finding_ids":[
				"finding_id_1"
			],
			"related_doc_ids":[
				"docId1"
			],
			"state":"ACTIVE",
			"error_message":null,
			"alert_history":[
				
			],
			"severity":null,
			"action_execution_results":[
				{
					"action_id":"action_id_1",
					"last_execution_time":1665693544996,
					"throttled_count":0
				}
			],
			"start_time":"2022-10-13T20:39:04.995023Z",
			"last_notification_time":"2022-10-13T20:39:04.995028Z",
			"end_time":"2022-10-13T20:39:04.995027Z",
			"acknowledged_time":"2022-10-13T20:39:04.995028Z"
		}
	],
	"total_alerts":1,
	"detectorType":"network"
}
```

### Response fields:

Alert state:
| state | description |
| --- | --- |
| ACTIVE | The alert is ongoing and unacknowledged. Alerts remain in this state until you acknowledge them, delete the trigger associated with the alert, or delete the monitor entirely.  |
| ACKNOWLEDGED | Someone has acknowledged the alert, but not fixed the root cause. |
| COMPLETED | The alert is no longer ongoing. Alerts enter this state after the corresponding trigger evaluates to false.  |
| ERROR | An error occurred while executing the trigger—usually the result of a a bad trigger or destination.  |
| DELETED | Someone deleted the monitor or trigger associated with this alert while the alert was ongoing.  |

**Comment by eirsep** [comment]
@petardz plz add a sample response structure.

**Comment by amsiglan** [comment]
@petardz @eirsep What are possible values for state in the response other than "ACTIVE"?

**Comment by amsiglan** [comment]
Would it be same as https://opensearch.org/docs/latest/monitoring-plugins/alerting/monitors/#work-with-alerts

**Comment by petardz** [comment]
@amsiglan Yes, same as on link you posted. Values are upper-case
