### ISSUE TITLE
[BUG] When we create a Detection using Detector API, it doesn't send Alerts when a Rule matches

### ISSUE THREAD

**Issue by marcoslin** [opensearch-project/security-analytics#577]
**What is the bug?**

When we create a Detection using [Detector API](https://opensearch.org/docs/latest/security-analytics/api-tools/detector-api/), it doesn't send Alerts when a Rule matches.

**How can one reproduce the bug?**

We create detection using:

```
POST /_plugins/_security_analytics/detectors HTTP/1.1
Host: <hostname>:9200
Content-Type: application/json
Authorization: Basic <key>
Content-Length: 1137
```

body:

```
{
  "name": "Detector Test from API",
  "detector_type": "apache_access",
  "enabled": true,
  "schedule": {
    "period": {
      "interval": 1,
      "unit": "MINUTES"
    }
  },
  "inputs": [
    {
      "detector_input": {
        "description": "Detector Test from API",
        "indices": [
          "xdrplus-*"
        ],
        "custom_rules": [
          {"id": "N1WwdooBBihv6QT0Pf3J"}
        ]
      }
    }
  ],
  "triggers": [
    {
      "ids":[],
      "types": ["apache_access"],
      "tags": [ ],
      "severity": "1",
      "actions": [
        {
          "destination_id": "0031aooBBihv6QT0-MD_",
          "subject_template": {
            "source": "source message",
            "lang": "mustache"
          },
          "name": "action test",
          "throttle_enabled": false,
          "message_template": {
            "source": "Triggered alert",
            "lang": "mustache"
          },
          "throttle": {
            "unit": "MINUTES",
            "value": 10
          }
        }
      ],
      "sev_levels": [ ],
      "name": "Triggered alert condition:  - Severity: 1 (Highest)"
    }
  ]
}
```

We checked the created [detector from API](https://github.com/opensearch-project/security-analytics/files/12611544/detector-from-api.txt) vs one [created from dashboard](https://github.com/opensearch-project/security-analytics/files/12611536/detector-from-dashboard.txt).

**What is the expected behavior?**

We expect the detector created from API to behave the same as the one created via dashboard to trigger alert when rule matches.

**What is your host/environment?**

We are using opensearchproject/opensearch:2.9.0 docker images.  We also tried version 2.7.0 and 2.8.0 and they have the same problem.

Any pointers on what we are doing wrong is greatly appreciated.

**Comment by amsiglan** [comment]
@marcoslin When a detector is created using the dashboard we make an additional API call before creating the detector which for applying mappings between the rule fields and the log fields. You will need to make that call separately when creating a detector using API call. Refer https://opensearch.org/docs/latest/security-analytics/api-tools/mappings-api/#example-request-1
