### ISSUE TITLE
[BUG] Findings are not generated during first run of the detector

### ISSUE THREAD

**Issue by amsiglan** [opensearch-project/security-analytics#606]
**What is the bug?**
After creating a detector, if data is ingested before the first execution of the detector, it does not generate any findings.

**How can one reproduce the bug?**
1. Create a detector with execution frequency of 1 min
2. Ingest log data within a minute
3. Ingest log data after a minute

**What is the expected behavior?**
There should be two set(s) of findings, one generated by the first run and one by the second run of the detector, but there is only one set of findings.

**What is your host/environment?**
 - OS: MacOS
 - Plugins: Security Analytics 2.10

**Do you have any screenshots?**
N/A

**Do you have any additional context?**
N/A

**Comment by sbcd90** [comment]
the issue is not `Findings are not generated during first run of the detector`.
the issue is `it takes a little more time for JobSweeper to sweep workflow job & schedule it`.
So, the delay remains same even if detector is scheduled every `1 min, 5 min, or 1 hour`.
