### ISSUE TITLE
[FEATURE] Run integration tests as part of the OpenSearch distribution

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/security-analytics#64]
**Is your feature request related to a problem?**
Following a problem in another plugin (https://github.com/opensearch-project/opensearch-build/issues/2043), and coming from https://github.com/opensearch-project/opensearch-build/issues/58, there's no automated testing that this plugin runs as part of the OpenSearch distribution.

**What solution would you like?**
Run integration tests as part of the distribution.

**Comment by sbcd90** [comment]
we support both `:integTest` & `:integTestRemote` gradle tasks which allows running integration tests as part of the OpenSearch distribution.
