### ISSUE TITLE
 [FEATURE] Return an empty response for getMappings API when there are no aliases applied

### ISSUE THREAD

**Issue by amsiglan** [opensearch-project/security-analytics#709]
**Is your feature request related to a problem?**
When no alias mappings are applied for an index, the GET mappingsView API throws an exception
`/_plugins/_security_analytics/mappings?indexName=c*`
Response:
`{"ok":false,"error":"[security_analytics_exception] No applied aliases found"}`

**What solution would you like?**
Return an empty result instead since it is not an actionable event for the user.

**What alternatives have you considered?**
N/A

**Do you have any additional context?**
N/A

**Comment by engechas** [comment]
Resolved by #724
