### ISSUE TITLE
[FEATURE] Creating custom Category and Edit default Category

### ISSUE THREAD

**Issue by saeed-mcu** [opensearch-project/security-analytics#715]
I think it can be very useful that as a user can define his own custom log type, he can also define a new category for it.

As a result, there will be a lot of customization

**Comment by goyamegh** [comment]
This functionality is available today. On the dashboards, you can go the URL: `_dashboards/app/opensearch_security_analytics_dashboards#/create-log-type`

This is available in 2.9 onwards.
