### ISSUE TITLE
[BUG] docData Must Not Be Null Error in Findings Page

### ISSUE THREAD

**Issue by jowg-amazon** [opensearch-project/security-analytics#718]
**What is the bug?**
If a detector generates a finding based on a document and its ID but then the document gets deleted, there is a `docData must not be null` error in the findings page and none of the findings appear.

**How can one reproduce the bug?**
1. Create a detector with a rule
2. Insert a document that generates a finding
3. Delete the document
4. Check the findings page

**What is your host/environment?**
 - OS: 2.9

**Comment by riysaxen-amzn** [comment]
closing in favor of 1325
