### ISSUE TITLE
[BUG] Creating a detector hangs. The detector is then silently created many hours later

### ISSUE THREAD

**Issue by engechas** [opensearch-project/security-analytics#825]
**What is the bug?**
This one's a 2-parter. The first part is that clusters under high load will hang when creating a detector. The networking tab of dev tools eventually shows a 504 GW timeout for the request.

In one occurrence of this, two detectors that were hung during creation did not appear until nearly a day later. Once they appeared, they began running normally.

**How can one reproduce the bug?**
1. Generate a high indexing workload against a cluster
2. Attempt to create a detector against the index being ingested to
3. Verify detector creation hangs

**What is the expected behavior?**
Detector creation should not hang. Detectors should not be created under the hood many hours later if the detector creation failed from the user perspective.

**What is your host/environment?**
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by praveensameneni** [comment]
Believe this [PR](https://github.com/opensearch-project/security-analytics/pull/871) addresses the issue. Feel free to re-open if it's still present
