### ISSUE TITLE
[BUG] Broken CI for 5 months

### ISSUE THREAD

**Issue by dblock** [opensearch-project/security-analytics#939]
**What is the bug?**

The last passing CI is https://github.com/opensearch-project/security-analytics/commit/b838dd8398a4eacdb122ca740827c0d1abebb3dd, which is over 5 months ago.

**What is the expected behavior?**

Passing builds.

**What is your host/environment?**

GHA

**Comment by praveensameneni** [comment]
@sbcd90 , can you check the security test workflow

**Comment by praveensameneni** [comment]
There were couple of issues with the CI failures - one was a cert issue and one related to flaky
Updated with latest PR and have few CI's passing for the past few weeks
https://github.com/opensearch-project/security-analytics/actions/runs/8887471505

**Comment by praveensameneni** [comment]
Closing the issue as we have stable integ tests and there are no distribution test failures.
